server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    dialect: ${SPRING_DATASOURCE_DIALECT}

  jpa:
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW}
    database: ${SPRING_JPA_DATABASE}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

jwt:
  secret-key: ${JWT_SECRET_KEY:ReleaseTest2024-K7x9P2q5M8n3Q6r1S4t7U0v2W5y8Z1a4B7c0D3e6F9g2H5i8J1k4L7m0N3p6R9s2T5u8V1w4Y7z0}
  expiration: ${JWT_EXPIRATION:86400000}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-request-uri: ${KAKAO_TOKEN_REQUEST_URI}
  user-info-request-uri: ${KAKAO_USER_INFO_REQUEST_URI}
